version: '3.5'

services:
  spring_mvc-db:
    image: postgres
    container_name: project2_boot-db
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=project2_boot
    ports:
      - "5507:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data